version: '3.8'

services:

  backend:
    build: ./ciklum-backend
    container_name: backend_container
    environment:
      SPRING_H2_CONSOLE_ENABLED: 'true'
      SPRING_DATASOURCE_URL: jdbc:h2:mem:listadb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: listauser
      SPRING_DATASOURCE_PASSWORD: listapassword
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    
  backend2:
    build: ./ciklum-backendTarea
    container_name: backend_container2
    environment:
      SPRING_H2_CONSOLE_ENABLED: 'true'
      SPRING_DATASOURCE_URL: jdbc:h2:mem:listadb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: listauser2
      SPRING_DATASOURCE_PASSWORD: listapassword2
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
  
  frontend:
    build: ./ciklum-frontend
    ports:
      - 4200:80

volumes:
  datos:
